language: C++
dist: bionic
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libeigen3-dev
script:
  - sudo apt purge --auto-remove cmake
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - sudo apt update
  - sudo apt install cmake
  - cmake --version
  - cmake -S . -B build
  - cmake --build build
  - cmake --build build --target test